server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/StarlightOnlineStore_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Oluwapelumi

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQL8Dialect

