spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update


    database-platform: org.hibernate.dialect.MySQL8Dialect