server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Starlightonlinestore_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Oluwapelumi

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect


  mail:
    host: smtp.gmail.com
    port: 465
    username: pelumijsh@gmail.com
    password: frkeirjbsowzzzbu

    properties:
      mail:
        smtp:
          #          ssl:
          #            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          ssl:
            enable: true




#server:
#  port: 8082
#spring:
#  datasource:
#    url: ${DATABASE_URL}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${USERNAME}
#    password: ${PASSWORD}
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#
#  mail:
#    host: ${MAIL_HOST}
#    port: ${MAIL_PORT}
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#
#    properties:
#      mail:
#        smtp:
##          ssl:
##            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000
#          ssl:
#            enable: true


#spring.mail.host=${MAIL_HOST}
#spring.mail.port=465
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=3000
#spring.mail.properties.mail.smtp.writetimeout=5000
#spring.mail.properties.mail.smtp.ssl.enable=true




#management:
#  endpoints:
#    web:
#      exposure:
#      include: '*'
#  info:
#    env:
#      enabled: true
#
#info:
#  application:
#    name: StarlightStores
#    description: online stor eapi
#    author: PerryJay
#    version: '@project.version@'
#spring:
#  profiles:
#    active: prod